"""
TriNetX PancPump Study - Script 08: Index Admission Length of Stay

Iteration-friendly LOS analysis. Loads matched pair lists generated by
Script 07 (psm_pairs_*.csv) and skips PSM entirely. Only requires:
  - master_patient_table.csv (for index dates)
  - encounter.csv (for inpatient admissions)

If pair caches aren't found, the script falls back to running PSM,
loading lab_clean and diagnosis as needed.

LOS = end_date - start_date in days for the inpatient encounter
(type IMP) that brackets the index date. Coalesces raw dates with
TriNetX-derived dates when raw dates are missing.

Compared via Wilcoxon rank-sum and t-test on log-LOS.

PI: Paul Kuo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import mannwhitneyu, ttest_ind
import os, warnings
warnings.filterwarnings('ignore')

# =============================================================================
# CONFIGURATION
# =============================================================================
DATA_DIR    = r"Z:\homes\Rachel Wolansky\Panc Pump\Data In"
OUTPUT_DIR  = r"Z:\homes\Rachel Wolansky\Panc Pump\Results"
RANDOM_SEED = 42

ERAS = {
    'Full cohort':   pd.Timestamp('2000-01-01'),
    'Past 10 years': pd.Timestamp('2016-01-01'),
    'Past 5 years':  pd.Timestamp('2021-01-01'),
}

INPATIENT_CODES = ['IMP', 'Inpatient', 'IP', 'INPATIENT']

def era_slug(era_label):
    return era_label.lower().replace(' ', '_')

def parse_dates(s):
    """Parse YYYYMMDD dates. Handles float coercion that happens when pandas
    reads an integer column containing NaN values (so 20210107 becomes
    20210107.0). Strips trailing '.0' before YYYYMMDD parsing."""
    s_str = s.astype(str).str.replace(r'\.0$', '', regex=True)
    d = pd.to_datetime(s_str, format='%Y%m%d', errors='coerce')
    if d.notna().sum() > len(d) * 0.3:
        return d
    return pd.to_datetime(s, errors='coerce')

# =============================================================================
# LOAD MASTER
# =============================================================================
print("\n" + "="*60)
print("LOADING MASTER")
print("="*60)

master = pd.read_csv(os.path.join(OUTPUT_DIR, "master_patient_table.csv"), low_memory=False)
master['index_date'] = pd.to_datetime(master['index_date'], errors='coerce')
print(f"  Master: {len(master):,}")

# =============================================================================
# LOAD OR COMPUTE MATCHED PAIRS
# =============================================================================
print("\n" + "="*60)
print("LOADING MATCHED PAIRS")
print("="*60)

pairs_per_era = {}
missing_eras  = []
for era_label in ERAS.keys():
    cache_path = os.path.join(OUTPUT_DIR, f"psm_pairs_{era_slug(era_label)}.csv")
    if os.path.exists(cache_path):
        pairs_per_era[era_label] = pd.read_csv(cache_path)
        print(f"  {era_label:15s}: loaded {len(pairs_per_era[era_label])} pairs "
              f"from {os.path.basename(cache_path)}")
    else:
        missing_eras.append(era_label)
        print(f"  {era_label:15s}: cache MISSING")

if missing_eras:
    print(f"\n  WARNING: {len(missing_eras)} era(s) missing pair cache.")
    print(f"  Falling back to PSM. This will be slow.")
    print(f"  Loading lab_clean and diagnosis...")
    lab_clean = pd.read_csv(os.path.join(OUTPUT_DIR, "lab_result_clean.csv"), low_memory=False)
    diagnosis = pd.read_csv(os.path.join(DATA_DIR, "diagnosis.csv"), low_memory=False)
    lab_clean['date'] = pd.to_datetime(lab_clean['date'], errors='coerce')
    diagnosis['date'] = pd.to_datetime(diagnosis['date'].astype(str),
                                         format='%Y%m%d', errors='coerce')

    from sklearn.linear_model import LogisticRegression
    from sklearn.preprocessing import StandardScaler

    PSM_DX_FLAGS = {
        'dm_type1':'E10', 'dm_type2':'E11', 'hypertension':'I10', 'cad':'I25',
        'heart_failure':'I50', 'pvd':'I73', 'dyslipidemia':'E78',
        'obesity':'E66', 'ckd':'N18', 'anemia':'D64',
    }
    HBAC1C_LOINCS = ['4548-4', '17856-6', '59261-8']
    CREAT_LOINCS  = ['2160-0', '38483-4']
    EGFR_LOINCS   = ['62238-1']

    def flag_dx_before_index(code_prefix, df_dx, df_pts):
        idx_map = df_pts.set_index('patient_id')['index_date'].to_dict()
        pid_set = set(df_pts['patient_id'])
        hits = df_dx[df_dx['code'].str.startswith(code_prefix, na=False) &
                     df_dx['patient_id'].isin(pid_set)].copy()
        hits['idx'] = hits['patient_id'].map(idx_map)
        hits = hits[hits['date'] < hits['idx']]
        return df_pts['patient_id'].isin(set(hits['patient_id'])).astype(int).values

    def get_baseline_lab(loinc_list, df_lab, df_pts, window=365):
        idx_map = df_pts.set_index('patient_id')['index_date'].to_dict()
        pid_set = set(df_pts['patient_id'])
        hits = df_lab[df_lab['code'].isin(loinc_list) &
                      df_lab['patient_id'].isin(pid_set) &
                      df_lab['lab_result_num_val'].notna()].copy()
        hits['idx']  = hits['patient_id'].map(idx_map)
        hits['days'] = (hits['date'] - hits['idx']).dt.days
        hits = hits[(hits['days'] >= -window) & (hits['days'] <= 0)]
        latest = (hits.sort_values('days')
                      .groupby('patient_id')['lab_result_num_val']
                      .last().reset_index())
        result = df_pts[['patient_id']].merge(latest, on='patient_id', how='left')
        return result['lab_result_num_val'].values

    def build_covariates(df_pts):
        cov = df_pts[['patient_id','cohort','index_date','age_at_index',
                      'sex','race','ethnicity']].copy()
        cov['sex_male']           = (cov['sex']=='M').astype(int)
        cov['race_white']         = cov['race'].str.contains('White', na=False).astype(int)
        cov['race_black']         = cov['race'].str.contains('Black', na=False).astype(int)
        cov['race_asian']         = cov['race'].str.contains('Asian', na=False).astype(int)
        cov['ethnicity_hispanic'] = cov['ethnicity'].str.contains('Hispanic', na=False).astype(int)
        for col, prefix in PSM_DX_FLAGS.items():
            cov[col] = flag_dx_before_index(prefix, diagnosis, df_pts)
        cov['baseline_hba1c']      = get_baseline_lab(HBAC1C_LOINCS, lab_clean, df_pts)
        cov['baseline_creatinine'] = get_baseline_lab(CREAT_LOINCS,  lab_clean, df_pts)
        cov['baseline_egfr']       = get_baseline_lab(EGFR_LOINCS,   lab_clean, df_pts)
        for col in ['baseline_hba1c','baseline_creatinine','baseline_egfr','age_at_index']:
            for cohort in ['KTP','SPK']:
                mask = (cov['cohort']==cohort) & cov[col].isna()
                cov.loc[mask, col] = cov[cov['cohort']==cohort][col].median()
        return cov.fillna(0)

    def run_psm(cov_df, caliper_sd=0.2, seed=RANDOM_SEED):
        psm_cols = [
            'age_at_index','sex_male','race_white','race_black','race_asian',
            'ethnicity_hispanic','dm_type1','dm_type2','hypertension','cad',
            'heart_failure','pvd','dyslipidemia','obesity','ckd','anemia',
            'baseline_hba1c','baseline_creatinine','baseline_egfr',
        ]
        X    = cov_df[psm_cols].values.astype(float)
        y    = (cov_df['cohort']=='KTP').astype(int).values
        X_sc = StandardScaler().fit_transform(X)
        lr   = LogisticRegression(max_iter=1000, random_state=seed, C=1.0)
        lr.fit(X_sc, y)
        ps   = lr.predict_proba(X_sc)[:,1]
        cov_df = cov_df.copy()
        cov_df['logit_ps'] = np.log(ps / (1 - ps + 1e-10))
        caliper = caliper_sd * cov_df['logit_ps'].std()
        ktp_df  = cov_df[cov_df['cohort']=='KTP'].sample(frac=1, random_state=seed).reset_index(drop=True)
        spk_df  = cov_df[cov_df['cohort']=='SPK'].reset_index(drop=True)
        matched, used = [], set()
        for _, row in ktp_df.iterrows():
            cands  = spk_df[~spk_df['patient_id'].isin(used)].copy()
            cands['diff'] = abs(cands['logit_ps'] - row['logit_ps'])
            within = cands[cands['diff'] <= caliper]
            if len(within) == 0: continue
            best = within.nsmallest(1,'diff').iloc[0]
            used.add(best['patient_id'])
            matched.append({'ktp_patient_id': row['patient_id'],
                            'spk_patient_id': best['patient_id']})
        return pd.DataFrame(matched)

    for era_label in missing_eras:
        cutoff  = ERAS[era_label]
        era_pts = master[master['index_date'] >= cutoff].copy()
        if (era_pts['cohort']=='KTP').sum() < 20:
            print(f"  {era_label}: too few KTP, skipping")
            continue
        print(f"  Running PSM for {era_label}...")
        cov_df   = build_covariates(era_pts)
        pairs_df = run_psm(cov_df)
        cache_path = os.path.join(OUTPUT_DIR, f"psm_pairs_{era_slug(era_label)}.csv")
        pairs_df.to_csv(cache_path, index=False)
        pairs_per_era[era_label] = pairs_df
        print(f"    {len(pairs_df)} pairs, saved to {os.path.basename(cache_path)}")

# =============================================================================
# LOAD ENCOUNTER
# =============================================================================
print("\n" + "="*60)
print("LOADING ENCOUNTER FILE")
print("="*60)

enc_path = os.path.join(DATA_DIR, "encounter.csv")
encounter = pd.read_csv(enc_path, low_memory=False)
print(f"  Rows: {len(encounter):,}")
print(f"  Columns: {list(encounter.columns)}")

# Parse dates: raw + TriNetX-derived
encounter['start_date'] = parse_dates(encounter['start_date'])
encounter['end_date']   = parse_dates(encounter['end_date'])
if 'start_date_derived_by_TriNetX' in encounter.columns:
    encounter['start_date_derived_by_TriNetX'] = parse_dates(
        encounter['start_date_derived_by_TriNetX'])
if 'end_date_derived_by_TriNetX' in encounter.columns:
    encounter['end_date_derived_by_TriNetX'] = parse_dates(
        encounter['end_date_derived_by_TriNetX'])

print(f"\n  Top values in 'type':")
print(encounter['type'].value_counts().head(8).to_string())

# Inpatient only
type_str = encounter['type'].astype(str).str.upper()
inpatient = encounter[type_str.isin([c.upper() for c in INPATIENT_CODES])].copy()
print(f"\n  Inpatient encounters: {len(inpatient):,}")

# Coalesce raw + derived dates
if 'start_date_derived_by_TriNetX' in inpatient.columns:
    inpatient['start_dt'] = inpatient['start_date'].fillna(
        inpatient['start_date_derived_by_TriNetX'])
else:
    inpatient['start_dt'] = inpatient['start_date']
if 'end_date_derived_by_TriNetX' in inpatient.columns:
    inpatient['end_dt'] = inpatient['end_date'].fillna(
        inpatient['end_date_derived_by_TriNetX'])
else:
    inpatient['end_dt'] = inpatient['end_date']

# Diagnostic
n_start = inpatient['start_dt'].notna().sum()
n_end   = inpatient['end_dt'].notna().sum()
n_both  = (inpatient['start_dt'].notna() & inpatient['end_dt'].notna()).sum()
print(f"\n  Inpatient with valid start_dt:  {n_start:,}")
print(f"  Inpatient with valid end_dt:    {n_end:,}")
print(f"  Inpatient with both:            {n_both:,}")

# Distribution of LOS values across the whole inpatient table (sanity check)
both_mask = inpatient['start_dt'].notna() & inpatient['end_dt'].notna()
if both_mask.sum() > 0:
    all_los = (inpatient.loc[both_mask, 'end_dt'] -
                inpatient.loc[both_mask, 'start_dt']).dt.days
    all_los = all_los[all_los >= 0]
    print(f"\n  Overall inpatient LOS distribution (all patients):")
    print(f"    median: {all_los.median():.1f}d  mean: {all_los.mean():.1f}d  "
          f"max: {all_los.max():.0f}d")

# Sample diagnostic: show inpatient encounters for first 3 matched patients
print(f"\n  Sample inpatient encounters for first 3 matched KTP patients:")
sample_pids = list(pairs_per_era['Full cohort']['ktp_patient_id'].head(3))
for pid in sample_pids:
    idx_d = master.loc[master['patient_id']==pid, 'index_date'].iloc[0]
    sample = inpatient[inpatient['patient_id']==pid][
        ['patient_id','start_dt','end_dt']].head(5)
    print(f"\n    patient_id={pid}, index_date={idx_d.date() if pd.notna(idx_d) else 'NaT'}")
    if len(sample) > 0:
        print(sample.to_string(index=False))
    else:
        print("      (no inpatient encounters)")

# =============================================================================
# LOS HELPER
# =============================================================================
def compute_los(pid, index_date):
    pid_encs = inpatient[inpatient['patient_id'] == pid]
    if len(pid_encs) == 0:
        return np.nan
    starts = pid_encs['start_dt']
    ends   = pid_encs['end_dt']
    mask = (starts <= index_date) & (ends >= index_date)
    if mask.sum() == 0:
        # Fallback: nearest start within 7 days before index
        before = pid_encs[(starts <= index_date) &
                           ((index_date - starts).dt.days <= 7)]
        if len(before) == 0: return np.nan
        row = before.loc[before['start_dt'].idxmax()]
    else:
        row = pid_encs[mask].iloc[0]
    if pd.isna(row['start_dt']) or pd.isna(row['end_dt']):
        return np.nan
    return max((row['end_dt'] - row['start_dt']).days, 1)

# =============================================================================
# MAIN LOOP
# =============================================================================
all_results   = []
los_data_long = []

for era_label, cutoff in ERAS.items():
    if era_label not in pairs_per_era:
        continue
    print("\n" + "="*60)
    print(f"ERA: {era_label.upper()}")
    print("="*60)
    pairs_df = pairs_per_era[era_label]
    n_pairs  = len(pairs_df)
    print(f"  Matched pairs: {n_pairs}")

    matched_ktp = list(pairs_df['ktp_patient_id'])
    matched_spk = list(pairs_df['spk_patient_id'])
    idx_map     = master.set_index('patient_id')['index_date'].to_dict()

    ktp_los = pd.Series([compute_los(p, idx_map.get(p))
                          for p in matched_ktp if p in idx_map]).dropna()
    spk_los = pd.Series([compute_los(p, idx_map.get(p))
                          for p in matched_spk if p in idx_map]).dropna()

    los_row = dict(Era=era_label, N_pairs=n_pairs, Outcome='LOS (days)')

    if len(ktp_los) < 5 or len(spk_los) < 5:
        print(f"  Too few LOS observations (KTP n={len(ktp_los)}, "
              f"SPK n={len(spk_los)})")
        los_row.update(n_ktp=len(ktp_los), n_spk=len(spk_los),
                       ktp_median=np.nan, ktp_iqr='',
                       spk_median=np.nan, spk_iqr='',
                       ktp_mean=np.nan, spk_mean=np.nan,
                       diff_median=np.nan, mw_p=np.nan, t_p_log=np.nan)
    else:
        for v in ktp_los: los_data_long.append({'Era':era_label,'Cohort':'KTP','LOS':v})
        for v in spk_los: los_data_long.append({'Era':era_label,'Cohort':'SPK','LOS':v})

        mw    = mannwhitneyu(ktp_los, spk_los, alternative='two-sided')
        t_log = ttest_ind(np.log(ktp_los), np.log(spk_los), equal_var=False)

        los_row.update(
            n_ktp=len(ktp_los), n_spk=len(spk_los),
            ktp_median=round(float(ktp_los.median()), 1),
            ktp_iqr=f"{ktp_los.quantile(0.25):.0f}-{ktp_los.quantile(0.75):.0f}",
            spk_median=round(float(spk_los.median()), 1),
            spk_iqr=f"{spk_los.quantile(0.25):.0f}-{spk_los.quantile(0.75):.0f}",
            ktp_mean=round(float(ktp_los.mean()), 1),
            spk_mean=round(float(spk_los.mean()), 1),
            diff_median=round(float(spk_los.median() - ktp_los.median()), 1),
            mw_p=round(float(mw.pvalue), 4),
            t_p_log=round(float(t_log.pvalue), 4),
        )
        sig = '*' if mw.pvalue < 0.05 else ''
        print(f"  KTP: median {los_row['ktp_median']}d (IQR {los_row['ktp_iqr']}), "
              f"mean {los_row['ktp_mean']}d, n={len(ktp_los)}")
        print(f"  SPK: median {los_row['spk_median']}d (IQR {los_row['spk_iqr']}), "
              f"mean {los_row['spk_mean']}d, n={len(spk_los)}")
        print(f"  Median diff (SPK-KTP): {los_row['diff_median']}d  "
              f"Wilcoxon p={los_row['mw_p']}{sig}  t(log) p={los_row['t_p_log']}")
    all_results.append(los_row)

# =============================================================================
# SAVE
# =============================================================================
print("\n" + "="*60)
print("SAVING")
print("="*60)
results_df = pd.DataFrame(all_results)
results_df.to_csv(os.path.join(OUTPUT_DIR, "los_results.csv"), index=False)
print("  -> Saved: los_results.csv")

if len(los_data_long) > 0:
    los_long_df = pd.DataFrame(los_data_long)
    los_long_df.to_csv(os.path.join(OUTPUT_DIR, "los_patient_level.csv"), index=False)
    print("  -> Saved: los_patient_level.csv")

    # Box plot
    fig, ax = plt.subplots(figsize=(10, 6))
    eras_present = [e for e in ERAS.keys() if e in los_long_df['Era'].unique()]
    positions, box_data, labels, colors = [], [], [], []
    pos = 0
    for era in eras_present:
        for cohort, c in [('KTP', '#2196F3'), ('SPK', '#E53935')]:
            d = los_long_df[(los_long_df['Era']==era) &
                              (los_long_df['Cohort']==cohort)]['LOS']
            if len(d) > 0:
                box_data.append(d.values)
                positions.append(pos); labels.append(f"{cohort}\n{era}")
                colors.append(c); pos += 1
        pos += 0.5

    bp = ax.boxplot(box_data, positions=positions, widths=0.7,
                     patch_artist=True, showfliers=False)
    for patch, c in zip(bp['boxes'], colors):
        patch.set_facecolor(c); patch.set_alpha(0.6)
    ax.set_xticks(positions); ax.set_xticklabels(labels, fontsize=9)
    ax.set_ylabel('Index admission LOS (days)', fontsize=11)
    ax.set_title('Index Admission Length of Stay by Cohort and Era',
                 fontsize=12, fontweight='bold')
    ax.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, "los_boxplot.png"), dpi=150)
    plt.close()
    print("  -> Saved: los_boxplot.png")

print("\n" + "="*60)
print("ABSTRACT TABLE FORMAT")
print("="*60)
print("\n  Index admission LOS, median days (IQR):")
for _, r in results_df.iterrows():
    if pd.isna(r.get('ktp_median', np.nan)):
        print(f"    {r['Era']:15s}: sparse"); continue
    p_str = '<0.001' if r['mw_p'] < 0.001 else f"{r['mw_p']:.3f}"
    sig   = '*' if r['mw_p'] < 0.05 else ''
    print(f"    {r['Era']:15s}: KTP {r['ktp_median']} ({r['ktp_iqr']})  "
          f"vs SPK {r['spk_median']} ({r['spk_iqr']})  Wilcoxon p={p_str}{sig}")

print("\n" + "="*60)
print("SCRIPT 08 COMPLETE")
print("="*60)
